modified the definition of model#
bbentzen/ipl pull request #9
Opened 2023-07-18 15:21 UTC by Huayu-Guo

modified the definition of model#

2023-07-18 15:22 UTC, Huayu-Guo commented
modified the definition of model#

2023-07-19 04:22 UTC, bbentzen requested changes
Please also add the revised semantics.lean file with the revised definition of model.

2023-07-20 09:07 UTC, Huayu-Guo commented
add semantics

2023-07-20 14:44 UTC, bbentzen commented
Reopened since I need to merge it.

2023-07-20 14:44 UTC, merged